### ISSUE TITLE
the size of tensor a(64) must match the size of tensor b (3) at non-sigleton dimension 1

### ISSUE THREAD

**Issue by kingback2019** [itewqq/PyTorch#2]
作者您好，当我在运行GCN_STN_BLN.py文件的时候，程序在此处
res=gradImg*self.Gradweight*Xo+Xo
报了错误：the size of tensor a(64) must match the size of tensor b (3) at non-singleton dimension 1
非常期待您的回复，不胜感激。

**Comment by itewqq** [comment]
@kingback2019 
这个版本的代码好像是有点问题的，但是我已经很久没做这个项目了，我自己的电脑也已经换过，原始的代码找不到了。其实这个程序的效果也并不好，没有太多值得学习的地方，非常抱歉T_T

**Comment by kingback2019** [comment]
嗯嗯，好吧，谢谢啦
